In [125]:
#pip install yfinance

### Downloading the yfinance in Python which is a Yahoo! Finance API. It's main components are:

- Ticker: single ticker data 
- 
Tickers: multiple tickers  dta
a- 
download: download market data for multiple ticke
r- s
Market: get information about a mar
k- et
WebSocket and AsyncWebSocket: live streaming 
d- ata
Search: quotes and news from s 
e- arch
Sector and Industry: sector and industry infor
m- ation
EquityQuery and Screener: build query to screen
 market

In [126]:
import yfinance as yf
import pandas as pd

In [127]:
symbol= yf.Ticker("BTC-USD")
df= symbol.history(period= "max", interval= "1h")
df.head(50)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2023-07-18 16:00:00+00:00,29904.332031,29956.478516,29556.427734,29715.876953,0,0.0,0.0
2023-07-18 17:00:00+00:00,29711.855469,29799.978516,29683.798828,29799.978516,0,0.0,0.0
2023-07-18 18:00:00+00:00,29820.083984,29919.382812,29794.798828,29901.966797,0,0.0,0.0
2023-07-18 19:00:00+00:00,29909.402344,29936.634766,29710.734375,29720.015625,0,0.0,0.0
2023-07-18 20:00:00+00:00,29719.406250,29794.064453,29704.521484,29777.044922,0,0.0,0.0
2023-07-18 21:00:00+00:00,29776.722656,29833.054688,29764.291016,29800.257812,0,0.0,0.0
2023-07-18 22:00:00+00:00,29797.849609,29823.927734,29770.392578,29821.093750,0,0.0,0.0
2023-07-18 23:00:00+00:00,29822.896484,29857.214844,29795.808594,29857.214844,0,0.0,0.0
2023-07-19 00:00:00+00:00,29862.046875,30067.421875,29845.177734,30056.330078,235968512,0.0,0.0
2023-07-19 01:00:00+00:00,30058.687500,30058.687500,29967.699219,30010.351562,65251328,0.0,0.0
2023-07-19 02:00:00+00:00,30017.410156,30030.314453,29978.253906,30016.218750,0,0.0,0.0
2023-07-19 03:00:00+00:00,30021.437500,30075.757812,30018.144531,30068.972656,118474752,0.0,0.0
2023-07-19 04:00:00+00:00,30068.244141,30184.181641,30068.244141,30109.687500,165735424,0.0,0.0
2023-07-19 05:00:00+00:00,30108.826172,30115.275391,30086.005859,30112.144531,27566080,0.0,0.0
2023-07-19 06:00:00+00:00,30108.021484,30108.021484,30017.324219,30049.136719,0,0.0,0.0
2023-07-19 07:00:00+00:00,30050.089844,30070.121094,29981.724609,30003.990234,0,0.0,0.0
2023-07-19 08:00:00+00:00,30001.449219,30015.792969,29915.250000,29928.345703,0,0.0,0.0
2023-07-19 09:00:00+00:00,29928.808594,30042.195312,29889.207031,30017.367188,89932800,0.0,0.0
2023-07-19 10:00:00+00:00,30013.648438,30033.943359,29987.998047,29987.998047,0,0.0,0.0
2023-07-19 11:00:00+00:00,29991.818359,30018.740234,29975.097656,30017.617188,0,0.0,0.0
2023-07-19 12:00:00+00:00,30014.953125,30018.892578,29904.675781,29953.650391,0,0.0,0.0
2023-07-19 13:00:00+00:00,29954.248047,30101.507812,29862.322266,30001.455078,0,0.0,0.0
2023-07-19 14:00:00+00:00,30002.044922,30023.251953,29814.851562,29824.255859,0,0.0,0.0
2023-07-19 15:00:00+00:00,29821.490234,29983.744141,29809.099609,29948.253906,151682048,0.0,0.0
2023-07-19 16:00:00+00:00,29953.332031,29968.042969,29875.769531,29891.080078,0,0.0,0.0
2023-07-19 17:00:00+00:00,29901.966797,30071.457031,29885.230469,29973.042969,0,0.0,0.0
2023-07-19 18:00:00+00:00,29988.904297,30082.566406,29948.634766,30075.363281,13475840,0.0,0.0
2023-07-19 19:00:00+00:00,30080.384766,30092.140625,30034.679688,30044.136719,0,0.0,0.0
2023-07-19 20:00:00+00:00,30045.333984,30047.351562,29959.787109,29959.787109,0,0.0,0.0
2023-07-19 21:00:00+00:00,29965.761719,29965.761719,29855.808594,29934.318359,198836224,0.0,0.0
2023-07-19 22:00:00+00:00,29930.939453,29957.199219,29854.792969,29882.158203,42775552,0.0,0.0
2023-07-19 23:00:00+00:00,29875.861328,29945.572266,29843.154297,29923.623047,90446848,0.0,0.0
2023-07-20 00:00:00+00:00,29915.250000,30005.066406,29906.693359,30003.343750,0,0.0,0.0
2023-07-20 01:00:00+00:00,30003.806641,30026.826172,29983.724609,30001.923828,0,0.0,0.0
2023-07-20 02:00:00+00:00,29993.212891,30042.144531,29981.923828,29992.757812,34529280,0.0,0.0
2023-07-20 03:00:00+00:00,29988.333984,29992.796875,29928.943359,29953.664062,0,0.0,0.0
2023-07-20 04:00:00+00:00,29949.968750,29979.890625,29931.259766,29966.494141,0,0.0,0.0
2023-07-20 05:00:00+00:00,29965.398438,30164.933594,29956.880859,30136.398438,243435520,0.0,0.0
2023-07-20 06:00:00+00:00,30135.488281,30195.531250,30100.250000,30124.849609,68959232,0.0,0.0
2023-07-20 07:00:00+00:00,30124.656250,30221.335938,30115.650391,30211.919922,13404362752,0.0,0.0
2023-07-20 08:00:00+00:00,30207.513672,30294.996094,30186.054688,30269.644531,32171907072,0.0,0.0
2023-07-20 09:00:00+00:00,30269.347656,30375.074219,30224.105469,30325.386719,35653705728,0.0,0.0
2023-07-20 10:00:00+00:00,30327.501953,30402.949219,30294.513672,30294.513672,0,0.0,0.0
2023-07-20 11:00:00+00:00,30296.380859,30308.978516,30266.218750,30291.507812,1719836672,0.0,0.0
2023-07-20 12:00:00+00:00,30292.824219,30306.746094,30223.041016,30227.347656,0,0.0,0.0
2023-07-20 13:00:00+00:00,30225.255859,30278.585938,30188.675781,30245.033203,16920125440,0.0,0.0
2023-07-20 14:00:00+00:00,30239.371094,30240.373047,29668.398438,29760.359375,0,0.0,0.0
2023-07-20 15:00:00+00:00,29782.138672,29839.986328,29726.177734,29808.396484,0,0.0,0.0
2023-07-20 16:00:00+00:00,29798.539062,29859.773438,29675.425781,29717.218750,259741696,0.0,0.0
2023-07-20 17:00:00+00:00,29712.189453,29801.123047,29702.093750,29755.357422,0,0.0,0.0

In [128]:
#Date starting from:
df.head(1)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2023-07-18 16:00:00+00:00,29904.332031,29956.478516,29556.427734,29715.876953,0,0.0,0.0

In [129]:
# Date extracted till:
df.tail(1)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2025-07-17 16:00:00+00:00,118921.492188,118959.757812,118582.09375,118731.945312,3840638976,0.0,0.0

In [130]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='object')

In [131]:
df= df.drop(['Dividends', 'Stock Splits'], axis= 1)
df.head(50)

,Open,High,Low,Close,Volume
Datetime,,,,,
2023-07-18 16:00:00+00:00,29904.332031,29956.478516,29556.427734,29715.876953,0
2023-07-18 17:00:00+00:00,29711.855469,29799.978516,29683.798828,29799.978516,0
2023-07-18 18:00:00+00:00,29820.083984,29919.382812,29794.798828,29901.966797,0
2023-07-18 19:00:00+00:00,29909.402344,29936.634766,29710.734375,29720.015625,0
2023-07-18 20:00:00+00:00,29719.406250,29794.064453,29704.521484,29777.044922,0
2023-07-18 21:00:00+00:00,29776.722656,29833.054688,29764.291016,29800.257812,0
2023-07-18 22:00:00+00:00,29797.849609,29823.927734,29770.392578,29821.093750,0
2023-07-18 23:00:00+00:00,29822.896484,29857.214844,29795.808594,29857.214844,0
2023-07-19 00:00:00+00:00,29862.046875,30067.421875,29845.177734,30056.330078,235968512
2023-07-19 01:00:00+00:00,30058.687500,30058.687500,29967.699219,30010.351562,65251328
2023-07-19 02:00:00+00:00,30017.410156,30030.314453,29978.253906,30016.218750,0
2023-07-19 03:00:00+00:00,30021.437500,30075.757812,30018.144531,30068.972656,118474752
2023-07-19 04:00:00+00:00,30068.244141,30184.181641,30068.244141,30109.687500,165735424
2023-07-19 05:00:00+00:00,30108.826172,30115.275391,30086.005859,30112.144531,27566080
2023-07-19 06:00:00+00:00,30108.021484,30108.021484,30017.324219,30049.136719,0
2023-07-19 07:00:00+00:00,30050.089844,30070.121094,29981.724609,30003.990234,0
2023-07-19 08:00:00+00:00,30001.449219,30015.792969,29915.250000,29928.345703,0
2023-07-19 09:00:00+00:00,29928.808594,30042.195312,29889.207031,30017.367188,89932800
2023-07-19 10:00:00+00:00,30013.648438,30033.943359,29987.998047,29987.998047,0
2023-07-19 11:00:00+00:00,29991.818359,30018.740234,29975.097656,30017.617188,0
2023-07-19 12:00:00+00:00,30014.953125,30018.892578,29904.675781,29953.650391,0
2023-07-19 13:00:00+00:00,29954.248047,30101.507812,29862.322266,30001.455078,0
2023-07-19 14:00:00+00:00,30002.044922,30023.251953,29814.851562,29824.255859,0
2023-07-19 15:00:00+00:00,29821.490234,29983.744141,29809.099609,29948.253906,151682048
2023-07-19 16:00:00+00:00,29953.332031,29968.042969,29875.769531,29891.080078,0
2023-07-19 17:00:00+00:00,29901.966797,30071.457031,29885.230469,29973.042969,0
2023-07-19 18:00:00+00:00,29988.904297,30082.566406,29948.634766,30075.363281,13475840
2023-07-19 19:00:00+00:00,30080.384766,30092.140625,30034.679688,30044.136719,0
2023-07-19 20:00:00+00:00,30045.333984,30047.351562,29959.787109,29959.787109,0
2023-07-19 21:00:00+00:00,29965.761719,29965.761719,29855.808594,29934.318359,198836224
2023-07-19 22:00:00+00:00,29930.939453,29957.199219,29854.792969,29882.158203,42775552
2023-07-19 23:00:00+00:00,29875.861328,29945.572266,29843.154297,29923.623047,90446848
2023-07-20 00:00:00+00:00,29915.250000,30005.066406,29906.693359,30003.343750,0
2023-07-20 01:00:00+00:00,30003.806641,30026.826172,29983.724609,30001.923828,0
2023-07-20 02:00:00+00:00,29993.212891,30042.144531,29981.923828,29992.757812,34529280
2023-07-20 03:00:00+00:00,29988.333984,29992.796875,29928.943359,29953.664062,0
2023-07-20 04:00:00+00:00,29949.968750,29979.890625,29931.259766,29966.494141,0
2023-07-20 05:00:00+00:00,29965.398438,30164.933594,29956.880859,30136.398438,243435520
2023-07-20 06:00:00+00:00,30135.488281,30195.531250,30100.250000,30124.849609,68959232
2023-07-20 07:00:00+00:00,30124.656250,30221.335938,30115.650391,30211.919922,13404362752
2023-07-20 08:00:00+00:00,30207.513672,30294.996094,30186.054688,30269.644531,32171907072
2023-07-20 09:00:00+00:00,30269.347656,30375.074219,30224.105469,30325.386719,35653705728
2023-07-20 10:00:00+00:00,30327.501953,30402.949219,30294.513672,30294.513672,0
2023-07-20 11:00:00+00:00,30296.380859,30308.978516,30266.218750,30291.507812,1719836672
2023-07-20 12:00:00+00:00,30292.824219,30306.746094,30223.041016,30227.347656,0
2023-07-20 13:00:00+00:00,30225.255859,30278.585938,30188.675781,30245.033203,16920125440
2023-07-20 14:00:00+00:00,30239.371094,30240.373047,29668.398438,29760.359375,0
2023-07-20 15:00:00+00:00,29782.138672,29839.986328,29726.177734,29808.396484,0
2023-07-20 16:00:00+00:00,29798.539062,29859.773438,29675.425781,29717.218750,259741696
2023-07-20 17:00:00+00:00,29712.189453,29801.123047,29702.093750,29755.357422,0

Here is the formula for the 3 lines.

Middle Band = 20 day simple moving average (SMA)

Upper Band = 20 day SMA + (20-day standard deviation of price x 2) 

Lower Band = 20 day SMA – (20-day standard deviation of price x 2)

How to calculate Bollinger Bands?
Traders use the formulas to calculate the three deviation:

How to calculate Bollinger Bands?
Standard deviation (SD) is the square root of the summation of the numbers in the population minus the mean divided by sample size. The next step after calculating the Standard deviation is calculating the upper and lower Bollinger bands. The Bollinger upper and lower bands are calculated by multiplying SD by two and both adding and subtracting the number from the value to plot upper and lower values.

The Bollinger Upper band is calculated by adding the 20-day simple moving average with the 20-day standard deviation multiplied by 2. Here is the formula for calculating the Bollinger Upper band:

BOLU=MA(TP,n)+m∗σ[TP,n]

The Bollinger Lower Band is calculated by subtracting the 20-day simple moving average from the 20-day standard deviation multiplied by 2. Here is the formula for calculating the Bollinger lower band:

BOLD=MA(TP,n)−m∗σ[TP,n]

Where,

BLOU = Bollinger Upper Band

BOLD = Bollinger Lower Band

MA = Moving Average

TP= Typical Price (High+Low+Close) / 3

N = Number of days in Moving Average (typically 20)

M = Number of SD (typically 2)

σ[TP,n] = SD over last n periods of TP

In [132]:
def BollingerBands(data, ma_period, n_std=2):
    
    sma= data.Close.rolling(ma_period).mean()
    
    hlc_avg= (data.High + data.Low + data.Close)/3
    
    # We calculated MA(TP,n):
    mean= hlc_avg.rolling(ma_period).mean()
    
    # calculated the standard deviation σ[TP,n]:
    std= hlc_avg.rolling(ma_period).std()
    
    # upper band
    upper_band= mean + std * n_std
    
    # lower band
    lower_band= mean - std * n_std
    
    return sma, upper_band, lower_band

In [133]:
df["SMA"], df["BBUp"], df["BBDown"]= BollingerBands(df, 20, 2)
df

,Open,High,Low,Close,Volume,SMA,BBUp,BBDown
Datetime,,,,,,,,
2023-07-18 16:00:00+00:00,29904.332031,29956.478516,29556.427734,29715.876953,0,NaN,NaN,NaN
2023-07-18 17:00:00+00:00,29711.855469,29799.978516,29683.798828,29799.978516,0,NaN,NaN,NaN
2023-07-18 18:00:00+00:00,29820.083984,29919.382812,29794.798828,29901.966797,0,NaN,NaN,NaN
2023-07-18 19:00:00+00:00,29909.402344,29936.634766,29710.734375,29720.015625,0,NaN,NaN,NaN
2023-07-18 20:00:00+00:00,29719.406250,29794.064453,29704.521484,29777.044922,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2025-07-17 12:00:00+00:00,118028.937500,118150.265625,117552.539062,117992.210938,11722498048,118694.035156,119769.570250,117639.887823
2025-07-17 13:00:00+00:00,117948.023438,118419.015625,117641.367188,118419.015625,10321600512,118658.520312,119701.782530,117594.430491
2025-07-17 14:00:00+00:00,118377.578125,118843.937500,118271.242188,118724.523438,14200840192,118613.007031,119571.760095,117633.188603
2025-07-17 15:00:00+00:00,118857.414062,119096.031250,118417.492188,118933.632812,7247192064,118596.901172,119500.664101,117657.548659
2025-07-17 16:00:00+00:00,118921.492188,118959.757812,118582.093750,118731.945312,3840638976,118539.604688,119317.431140,117752.819641

In [134]:
df= df.dropna()
df

,Open,High,Low,Close,Volume,SMA,BBUp,BBDown
Datetime,,,,,,,,
2023-07-19 11:00:00+00:00,29991.818359,30018.740234,29975.097656,30017.617188,0,29938.580469,30182.655068,29684.801572
2023-07-19 12:00:00+00:00,30014.953125,30018.892578,29904.675781,29953.650391,0,29950.469141,30176.793624,29712.277535
2023-07-19 13:00:00+00:00,29954.248047,30101.507812,29862.322266,30001.455078,0,29960.542969,30172.074774,29739.714028
2023-07-19 14:00:00+00:00,30002.044922,30023.251953,29814.851562,29824.255859,0,29956.657422,30171.693910,29741.635257
2023-07-19 15:00:00+00:00,29821.490234,29983.744141,29809.099609,29948.253906,151682048,29968.069336,30164.272772,29761.513491
...,...,...,...,...,...,...,...,...
2025-07-17 12:00:00+00:00,118028.937500,118150.265625,117552.539062,117992.210938,11722498048,118694.035156,119769.570250,117639.887823
2025-07-17 13:00:00+00:00,117948.023438,118419.015625,117641.367188,118419.015625,10321600512,118658.520312,119701.782530,117594.430491
2025-07-17 14:00:00+00:00,118377.578125,118843.937500,118271.242188,118724.523438,14200840192,118613.007031,119571.760095,117633.188603
2025-07-17 15:00:00+00:00,118857.414062,119096.031250,118417.492188,118933.632812,7247192064,118596.901172,119500.664101,117657.548659
2025-07-17 16:00:00+00:00,118921.492188,118959.757812,118582.093750,118731.945312,3840638976,118539.604688,119317.431140,117752.819641

In [135]:
import plotly.graph_objs as go
import plotly.offline as pyo

In [136]:
# Create a plotly Figure:
fig= go.Figure( )

#Add the price Chart
fig.add_trace(go.Scatter(x= df.index, y= df['Close'], mode= 'lines', name= 'Close Price'))

#Add the Upper and the Lower Bollinger Bands
fig.add_trace(go.Scatter(x= df.index, y= df['BBUp'], mode= 'lines', name= 'Upper Bollinger Band', line= dict(color= 'red')))
fig.add_trace(go.Scatter(x= df.index, y= df['BBDown'], mode= 'lines', name= 'Lower Bollinger Band', line= dict(color= 'green')))

#Add the middle line for SMA:
fig.add_trace(go.Scatter(x= df.index, y= df['SMA'], mode= 'lines', name= 'SMA', line= dict(color= 'blue')))

#Customize
fig.update_layout(title= "Bollinger Bands",
                 xaxis_title= 'Timestamp',
                 yaxis_title= 'Close Price',
                 showlegend= True,
                 width= 1600,
                 height= 800)

#Show the chart
pyo.plot(fig, filename= "BollingerBands.html")

'BollingerBands.html'

In [137]:
#Calculate the Bollinger bands:
df['BbWidth']= (df["BBUp"]- df["BBDown"])/df["SMA"]
df

C:\Users\samra\AppData\Local\Temp\ipykernel_16004\858655087.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Open,High,Low,Close,Volume,SMA,BBUp,BBDown,BbWidth
Datetime,,,,,,,,,
2023-07-19 11:00:00+00:00,29991.818359,30018.740234,29975.097656,30017.617188,0,29938.580469,30182.655068,29684.801572,0.016629
2023-07-19 12:00:00+00:00,30014.953125,30018.892578,29904.675781,29953.650391,0,29950.469141,30176.793624,29712.277535,0.015509
2023-07-19 13:00:00+00:00,29954.248047,30101.507812,29862.322266,30001.455078,0,29960.542969,30172.074774,29739.714028,0.014431
2023-07-19 14:00:00+00:00,30002.044922,30023.251953,29814.851562,29824.255859,0,29956.657422,30171.693910,29741.635257,0.014356
2023-07-19 15:00:00+00:00,29821.490234,29983.744141,29809.099609,29948.253906,151682048,29968.069336,30164.272772,29761.513491,0.013440
...,...,...,...,...,...,...,...,...,...
2025-07-17 12:00:00+00:00,118028.937500,118150.265625,117552.539062,117992.210938,11722498048,118694.035156,119769.570250,117639.887823,0.017943
2025-07-17 13:00:00+00:00,117948.023438,118419.015625,117641.367188,118419.015625,10321600512,118658.520312,119701.782530,117594.430491,0.017760
2025-07-17 14:00:00+00:00,118377.578125,118843.937500,118271.242188,118724.523438,14200840192,118613.007031,119571.760095,117633.188603,0.016344
2025-07-17 15:00:00+00:00,118857.414062,119096.031250,118417.492188,118933.632812,7247192064,118596.901172,119500.664101,117657.548659,0.015541
2025-07-17 16:00:00+00:00,118921.492188,118959.757812,118582.093750,118731.945312,3840638976,118539.604688,119317.431140,117752.819641,0.013199

In [138]:
#pip install pandas_ta
import pandas_ta as ta

In [139]:
df["RSI"]= ta.momentum.rsi(df['Close'], window= 14)
df

C:\Users\samra\AppData\Local\Temp\ipykernel_16004\1046129084.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Open,High,Low,Close,Volume,SMA,BBUp,BBDown,BbWidth,RSI
Datetime,,,,,,,,,,
2023-07-19 11:00:00+00:00,29991.818359,30018.740234,29975.097656,30017.617188,0,29938.580469,30182.655068,29684.801572,0.016629,NaN
2023-07-19 12:00:00+00:00,30014.953125,30018.892578,29904.675781,29953.650391,0,29950.469141,30176.793624,29712.277535,0.015509,NaN
2023-07-19 13:00:00+00:00,29954.248047,30101.507812,29862.322266,30001.455078,0,29960.542969,30172.074774,29739.714028,0.014431,NaN
2023-07-19 14:00:00+00:00,30002.044922,30023.251953,29814.851562,29824.255859,0,29956.657422,30171.693910,29741.635257,0.014356,NaN
2023-07-19 15:00:00+00:00,29821.490234,29983.744141,29809.099609,29948.253906,151682048,29968.069336,30164.272772,29761.513491,0.013440,NaN
...,...,...,...,...,...,...,...,...,...,...
2025-07-17 12:00:00+00:00,118028.937500,118150.265625,117552.539062,117992.210938,11722498048,118694.035156,119769.570250,117639.887823,0.017943,43.721262
2025-07-17 13:00:00+00:00,117948.023438,118419.015625,117641.367188,118419.015625,10321600512,118658.520312,119701.782530,117594.430491,0.017760,49.135247
2025-07-17 14:00:00+00:00,118377.578125,118843.937500,118271.242188,118724.523438,14200840192,118613.007031,119571.760095,117633.188603,0.016344,52.646804
2025-07-17 15:00:00+00:00,118857.414062,119096.031250,118417.492188,118933.632812,7247192064,118596.901172,119500.664101,117657.548659,0.015541,54.939843
2025-07-17 16:00:00+00:00,118921.492188,118959.757812,118582.093750,118731.945312,3840638976,118539.604688,119317.431140,117752.819641,0.013199,52.308805

In [140]:
signal_df= df.dropna(subset= ['RSI']).copy()
signal_df

,Open,High,Low,Close,Volume,SMA,BBUp,BBDown,BbWidth,RSI
Datetime,,,,,,,,,,
2023-07-20 01:00:00+00:00,30003.806641,30026.826172,29983.724609,30001.923828,0,29971.042383,30076.596635,29866.899003,0.006997,51.955968
2023-07-20 02:00:00+00:00,29993.212891,30042.144531,29981.923828,29992.757812,34529280,29968.223438,30067.270822,29870.969608,0.006550,51.067350
2023-07-20 03:00:00+00:00,29988.333984,29992.796875,29928.943359,29953.664062,0,29965.707129,30061.526240,29870.699802,0.006368,47.347798
2023-07-20 04:00:00+00:00,29949.968750,29979.890625,29931.259766,29966.494141,0,29967.614551,30061.694890,29871.139681,0.006359,48.669191
2023-07-20 05:00:00+00:00,29965.398438,30164.933594,29956.880859,30136.398438,243435520,29973.566113,30080.765226,29862.384123,0.007286,62.198700
...,...,...,...,...,...,...,...,...,...,...
2025-07-17 12:00:00+00:00,118028.937500,118150.265625,117552.539062,117992.210938,11722498048,118694.035156,119769.570250,117639.887823,0.017943,43.721262
2025-07-17 13:00:00+00:00,117948.023438,118419.015625,117641.367188,118419.015625,10321600512,118658.520312,119701.782530,117594.430491,0.017760,49.135247
2025-07-17 14:00:00+00:00,118377.578125,118843.937500,118271.242188,118724.523438,14200840192,118613.007031,119571.760095,117633.188603,0.016344,52.646804
2025-07-17 15:00:00+00:00,118857.414062,119096.031250,118417.492188,118933.632812,7247192064,118596.901172,119500.664101,117657.548659,0.015541,54.939843
2025-07-17 16:00:00+00:00,118921.492188,118959.757812,118582.093750,118731.945312,3840638976,118539.604688,119317.431140,117752.819641,0.013199,52.308805

In [141]:
def backtest_bollingerBands(df, rsi_threshold_low= 30, rsi_threshold_high= 70, bb_width_threshold= 0.0015):
    df['Signal']= 0
    for i in range(1, len(df)):
        #Previous Candle Conditions for Long Signal:
        prev_candle_closes_below_bb= df['Close'].iloc[i-1] < df['BBDown'].iloc[i-1]
        prev_rsi_below_thr= df['RSI'].iloc[i-1] < rsi_threshold_low
        #Current Candle
        closes_above_prev_high= df['Close'].iloc[i] > df['High'].iloc[i-1]
        bb_width_greater_threshold= df['BbWidth'].iloc[i] > bb_width_threshold
        #SMA trend
        #price_moves_above_the_SMA= df['Close'].iloc[i] > df['SMA'].iloc[i]

        #Combine Conditions
        if(prev_candle_closes_below_bb and
          prev_rsi_below_thr and
          closes_above_prev_high and
          bb_width_greater_threshold 
          # and price_moves_above_the_SMA
          ):
            df.at[df.index[i],'Signal']= 1 #Buy Signal
        
        #Previous Candle Conditions for Short Signal:
        prev_candle_closes_above_bb= df['Close'].iloc[i-1] > df['BBUp'].iloc[i-1]
        prev_rsi_above_thr= df['RSI'].iloc[i-1] > rsi_threshold_high
        #Current Candle
        closes_below_prev_low= df['Close'].iloc[i] < df['Low'].iloc[i-1]
        bb_width_greater_threshold= df['BbWidth'].iloc[i] > bb_width_threshold
        #SMA trend
        #price_moves_below_the_SMA= df['Close'].iloc[i] < df['SMA'].iloc[i]

        #Combine Conditions
        if(prev_candle_closes_above_bb and
          prev_rsi_above_thr and
          closes_below_prev_low and
          bb_width_greater_threshold 
          # and price_moves_below_the_SMA
          ):
            df.at[df.index[i],'Signal']= -1 #Sell Signal
    return df

In [147]:
backtest_bollingerBands(signal_df, 30, 70, 0.03)
# it gets very selective with bb_width_threshold as 0.03

C:\Users\samra\AppData\Local\Temp\ipykernel_16004\199902120.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Open,High,Low,Close,Volume,SMA,BBUp,BBDown,BbWidth,RSI,Signal
Datetime,,,,,,,,,,,
2023-07-23 19:00:00+00:00,30257.757812,30330.640625,30025.451172,30079.740234,658966528,29934.044922,30128.139845,29732.848892,0.013205,60.082434,0
2023-08-01 05:00:00+00:00,28856.568359,28913.261719,28853.412109,28913.261719,46772224,29191.614258,29540.349458,28854.517078,0.023494,32.544585,0
2023-08-08 21:00:00+00:00,29991.501953,30156.957031,29837.566406,29847.212891,922994688,29448.739746,30037.477984,28854.680544,0.040165,69.095133,0
2023-08-14 02:00:00+00:00,29241.568359,29315.390625,29124.105469,29276.228516,1169799680,29349.241113,29458.933526,29241.314261,0.007415,36.991709,0
2023-08-14 17:00:00+00:00,29620.431641,29636.363281,29462.273438,29465.652344,295625728,29380.240820,29575.394359,29183.070094,0.013353,55.142850,0
...,...,...,...,...,...,...,...,...,...,...,...
2025-06-16 09:00:00+00:00,107196.937500,107231.554688,106939.039062,106939.039062,301731840,105872.588281,107232.162002,104469.849977,0.026091,67.513831,0
2025-06-21 20:00:00+00:00,102283.765625,102879.710938,102264.117188,102852.406250,19210240,103455.765234,104241.211224,102699.099974,0.014906,38.680594,0
2025-06-22 17:00:00+00:00,99690.164062,100305.460938,99497.062500,99566.679688,934981632,101831.869922,104297.863498,99409.951346,0.048000,28.720705,0
2025-06-24 00:00:00+00:00,105407.609375,105533.234375,105005.375000,105202.179688,0,102647.797266,105398.411431,99704.747944,0.055468,68.654218,0
2025-07-04 17:00:00+00:00,107843.054688,107932.210938,107766.484375,107918.890625,167186432,108830.362500,110187.568620,107559.160286,0.024151,34.731647,0

In [148]:
from plotly.subplots import make_subplots
# Visualizing the data:
# Create a plot with 2 rows:
fig= make_subplots(rows= 2 , cols= 1)

#Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x= signal_df.index,
                            open= signal_df['Open'],
                            high= signal_df['High'],
                            low= signal_df['Low'],
                            close= signal_df['Close']),
             row= 1, col= 1)

#Add Bollinger Bands, SMA lines on the same subplot:
fig.add_trace(go.Scatter(x= signal_df.index,
                        y= signal_df['BBDown'],
                        line= dict(color='darkturquoise', width= 1),
                        name= "Bollinger Band Down"),
             row= 1, col= 1)
fig.add_trace(go.Scatter(x= signal_df.index,
                        y= signal_df['BBUp'],
                        line= dict(color='darkturquoise', width= 1),
                        name= "Bollinger Band Up"),
             row= 1, col= 1)
fig.add_trace(go.Scatter(x= signal_df.index,
                        y= signal_df['SMA'],
                        line= dict(color='blue', width= 1),
                        name= "SMA"),
             row= 1, col= 1)


# Mark Buy Signals
buy_signals = signal_df[signal_df['Signal'] == 1]
fig.add_trace(go.Scatter(mode='markers', x=buy_signals.index, 
                         y=buy_signals['Low'] -1e-4,
                         marker=dict(color='green', size=10, symbol='triangle-up'),
                         name='Buy Signal'), row= 1, col= 1)

# Mark Sell Signals
sell_signals = signal_df[signal_df['Signal'] == -1]
fig.add_trace(go.Scatter(mode='markers', x=sell_signals.index, 
                         y=sell_signals['High'] + 1e-4,
                         marker=dict(color='red', size=10, symbol='triangle-down'),
                         name='Sell Signal'), row= 1, col= 1)

#Add RSI indicator in the next subplot
fig.add_trace(go.Scatter(x= signal_df.index,
                        y= signal_df['RSI'],
                        line= dict(color='green', width= 1),
                        name= "RSI"),
             row= 2, col= 1)


fig.update_layout(width= 2000, height= 1600,
                  title_text="Candlestick with Bollinger Bands, SMA, and RSI",
                  )

#fig.show()
# Improve readability by controlling x-axis range and enabling zoom
#fig.update_xaxes(rangeslider_thickness=0.05)
#Show the chart
pyo.plot(fig, filename= "BollingerBands_BuySellSignals.html")

'BollingerBands_BuySellSignals.html'

In [149]:
df.shape

(17500, 10)

In [150]:
signal_df= signal_df[signal_df['Signal']!= 0]
signal_df.shape

(0, 11)

In [151]:
signal_df.head(50)

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, SMA, BBUp, BBDown, BbWidth, RSI, Signal]
Index: []