
## Collecting Data from API

Opening conda prompt:

1. cd /d D:\crypto_trading

2. conda activate cryptotrading

3. jupyter notebook

https://developers.binance.com/docs/binance-spot-api-docs

https://www.bitmex.com/app/apiOverview

In [1]:
# import necessary files
import logging
from exchanges.binance import BinanceClient
from exchanges.coinbase import CoinbaseClient
from database import Hdf5Client
from utils.time_convertor import *
import pandas as pd
import numpy as np
import time

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 1000)

In [18]:
#import and format the data
h5_db= Hdf5Client("Binance")
data= h5_db.get_data("BTCUSDT", from_time= 0, to_time= int(time.time() * 1000))
data= resample_timeframe(data, "1h")

In [19]:
# perform operations on the dataframe
data["high_low_average"]= (data["high"] +  data["low"])/2
data

                          open       high        low      close        volume  high_low_average
timestamp
2025-03-30 10:00:00   83285.53   83359.90   83064.17   83120.87    223.190610         83212.035
2025-03-30 11:00:00   83120.86   83360.31   82989.27   83111.76    334.935950         83174.790
2025-03-30 12:00:00   83109.65   83268.05   82989.26   83072.76    356.536890         83128.655
2025-03-30 13:00:00   83068.13   83155.17   82662.01   82678.42   1050.992850         82908.590
2025-03-30 14:00:00   82678.42   83043.59   82630.02   82803.28    466.767080         82836.805
2025-03-30 15:00:00   82803.28   83067.90   82732.02   82729.57    280.141080         82899.960
2025-03-30 16:00:00   82710.48   82816.00   82201.89   82284.01    603.144990         82508.945
2025-03-30 17:00:00   82250.00   82577.99   82059.70   82415.53    398.110750         82318.845
2025-03-30 18:00:00   82415.53   82799.99   82415.54   82729.65    321.945930         82607.765
2025-03-30 19:00:00   82707.83   82908.11   82550.05   82548.81    258.331760         82729.080
2025-03-30 20:00:00   82544.80   82650.95   82400.01   82554.73    201.030050         82525.480
2025-03-30 21:00:00   82554.73   82703.94   82069.41   82237.68    258.821660         82386.675
2025-03-30 22:00:00   82086.00   82757.70   81577.86   82438.00    997.389990         82167.780
2025-03-30 23:00:00   82391.98   82442.94   81964.95   82389.99    621.081980         82203.945
2025-03-31 00:00:00   82368.48   82444.89   81333.98   81646.89   1156.904700         81889.435
2025-03-31 01:00:00   81534.78   82272.72   81543.25   81953.03    778.608830         81907.985
2025-03-31 02:00:00   81900.00   82179.25   81644.00   81922.30    652.558370         81911.625
2025-03-31 03:00:00   81906.00   82030.00   81490.01   81530.00    549.387110         81760.005
2025-03-31 04:00:00   81529.09   81879.16   81417.47   81846.01    489.047800         81648.315
2025-03-31 05:00:00   81830.00   82305.57   81846.00   82166.99    520.567410         82075.785
2025-03-31 06:00:00   82166.98   82267.66   81938.55   82052.83    641.586310         82103.105
2025-03-31 07:00:00   82046.00   82303.58   81765.75   81933.51    776.648170         82034.665
2025-03-31 08:00:00   81908.19   82263.74   81914.38   81899.15    762.807570         82089.060
2025-03-31 09:00:00   81889.34   81960.56   81371.68   81455.58    965.895570         81666.120
2025-03-31 10:00:00   81451.90   82215.91   81325.68   82174.16    713.595130         81770.795
2025-03-31 11:00:00   82174.16   82272.00   81893.04   82205.51    980.634120         82082.520
2025-03-31 12:00:00   82185.63   83169.82   81939.36   82768.74   1527.489470         82554.590
2025-03-31 13:00:00   82706.58   82866.02   81761.36   82507.99   2027.952580         82313.690
2025-03-31 14:00:00   82507.49   83746.23   82507.99   83499.18   2160.575470         83127.110
2025-03-31 15:00:00   83499.18   83943.08   83411.39   83418.78   1241.909230         83677.235
2025-03-31 16:00:00   83418.78   83694.29   83273.18   83288.89    658.286560         83483.735
2025-03-31 17:00:00   83261.76   83545.55   82586.00   82680.34    667.392630         83065.775
2025-03-31 18:00:00   82676.00   83566.00   82680.35   83291.42    810.730870         83123.175
2025-03-31 19:00:00   83282.00   83443.38   82412.81   82462.27    798.209250         82928.095
2025-03-31 20:00:00   82405.02   82846.20   82376.82   82431.32    701.198120         82611.510
2025-03-31 21:00:00   82422.00   82752.18   82431.32   82563.99    342.528650         82591.750
2025-03-31 22:00:00   82553.00   82571.98   82280.15   82409.99    260.876470         82426.065
2025-03-31 23:00:00   82388.21   82886.80   82295.86   82550.01    383.748460         82591.330
2025-04-01 00:00:00   82490.76   82837.38   82432.74   82651.10    526.959220         82635.060
2025-04-01 01:00:00   82605.34   82741.80   82470.01   82704.20    440.090930         82605.905
2025-04-01 02:00:00   82685.24   83120.00   82649.34   83100.00    522.782460         82884.670
2025-04-01 03:00:00   83065.23   83256.80   82926.10   82962.84    526.153630         83091.450
2025-04-01 04:00:00   82914.39   83235.96   82887.01   83060.00    425.378740         83061.485
2025-04-01 05:00:00   83031.57   83329.99   82994.08   83006.67    348.443640         83162.035
2025-04-01 06:00:00   83000.01   83494.25   82900.01   83454.76    425.660160         83197.130
2025-04-01 07:00:00   83454.75   83597.07   83387.07   83445.50    622.585510         83492.070
2025-04-01 08:00:00   83410.00   84207.55   83445.50   84121.94   1217.292790         83826.525
2025-04-01 09:00:00   84121.93   84395.46   84121.94   84362.00   1018.971860         84258.700
2025-04-01 10:00:00   84311.68   84504.74   84169.81   84175.99    914.761180         84337.275
2025-04-01 11:00:00   84161.58   84203.00   83846.38   83930.30    854.543510         84024.690
2025-04-01 12:00:00   83924.52   84154.22   83628.16   83615.26    734.992560         83891.190
2025-04-01 13:00:00   83596.00   83912.62   83430.69   83618.23   1152.681040         83671.655
2025-04-01 14:00:00   83480.00   84350.00   82637.99   84195.92   2522.860470         83493.995
2025-04-01 15:00:00   84182.89   85499.55   84195.92   85280.87   2484.930750         84847.735
2025-04-01 16:00:00   85275.21   85493.00   84815.32   85119.99   1208.484920         85154.160
2025-04-01 17:00:00   85028.12   85333.33   84904.25   85117.85    775.262400         85118.790
2025-04-01 18:00:00   85038.01   85183.46   84726.64   85126.68    742.895530         84955.050
2025-04-01 19:00:00   85095.97   85184.89   84836.97   84972.01    897.453260         85010.930
2025-04-01 20:00:00   84920.48   85350.00   84782.36   85231.28    528.396380         85066.180
2025-04-01 21:00:00   85231.28   85476.86   85138.01   85223.84    325.841410         85307.435
2025-04-01 22:00:00   85219.90   85483.38   85114.88   85099.99    477.113020         85299.130
2025-04-01 23:00:00   85084.80   85579.46   84991.80   85158.34    495.861600         85285.630
2025-04-02 00:00:00   85158.35   85255.95   84940.78   84964.49    472.950930         85098.365
2025-04-02 01:00:00   84956.31   85213.12   84870.85   85147.30    597.768960         85041.985
2025-04-02 02:00:00   85101.08   85174.89   84665.22   84714.36    850.774360         84920.055
2025-04-02 03:00:00   84706.21   84904.00   84532.43   84550.00    475.509660         84718.215
2025-04-02 04:00:00   84517.00   84726.42   84475.46   84607.00    444.662260         84600.940
2025-04-02 05:00:00   84567.60   84607.00   84117.15   84100.00    550.684820         84362.075
2025-04-02 06:00:00   84046.00   84371.59   83931.29   84125.99    646.497800         84151.440
2025-04-02 07:00:00   84120.00   84462.16   84039.79   84426.33    642.707380         84250.975
2025-04-02 08:00:00   84351.77   84762.72   84262.74   84677.04    535.256650         84512.730
2025-04-02 09:00:00   84635.60   85450.00   84677.04   85019.62    910.863510         85063.520
2025-04-02 10:00:00   85015.50   85299.45   84851.98   84867.92    592.830320         85075.715
2025-04-02 11:00:00   84746.18   84985.77   84558.69   84566.91    463.522710         84772.230
2025-04-02 12:00:00   84554.43   85054.78   84487.90   85049.99    742.570820         84771.340
2025-04-02 13:00:00   84983.68   86136.36   84531.34   85215.82   2792.280520         85333.850
2025-04-02 14:00:00   85181.52   86000.00   85215.79   85877.75   2062.013420         85607.895
2025-04-02 15:00:00   85811.20   87333.00   85877.74   86757.67   5585.702140         86605.370
2025-04-02 16:00:00   86697.78   87221.99   86603.77   87065.18   2549.141960         86912.880
2025-04-02 17:00:00   87039.92   87333.00   86391.97   86615.33   2025.448110         86862.485
2025-04-02 18:00:00   86581.55   86751.79   86236.46   86286.02    685.232900         86494.125
2025-04-02 19:00:00   86286.03   87000.00   86206.56   86900.02    812.773360         86603.280
2025-04-02 20:00:00   86774.82   88500.00   85299.48   85659.99   7832.634990         86899.740
2025-04-02 21:00:00   85615.64   85743.22   84260.00   84855.99   1793.310350         85001.610
2025-04-02 22:00:00   84582.79   84855.98   82737.64   82821.59   3036.674270         83796.810
2025-04-02 23:00:00   82560.59   82845.42   82384.65   82516.29   2829.644800         82615.035
2025-04-03 00:00:00   82436.40   83424.72   82212.01   83227.55   1848.780370         82818.365
2025-04-03 01:00:00   83190.00   83998.02   83138.90   83761.62   1735.380820         83568.460
2025-04-03 02:00:00   83750.94   83894.91   83284.44   83768.01   1422.271460         83589.675
2025-04-03 03:00:00   83743.89   83792.58   83349.66   83483.97    638.138130         83571.120
2025-04-03 04:00:00   83454.94   83735.85   83300.00   83558.80    630.552660         83517.925
2025-04-03 05:00:00   83556.93   83709.48   83348.26   83343.75    457.594970         83528.870
2025-04-03 06:00:00   83300.00   83415.47   83008.74   83058.65    568.508340         83212.105
2025-04-03 07:00:00   83036.47   83498.10   83025.01   83456.75    774.524070         83261.555
2025-04-03 08:00:00   83456.74   83788.23   83456.76   83679.99    821.936770         83622.495
2025-04-03 09:00:00   83677.10   83766.69   83449.92   83483.05    539.185410         83608.305
2025-04-03 10:00:00   83469.49   83749.99   83170.66   83220.01   1239.616160         83460.325
2025-04-03 11:00:00   83129.71   83347.39   83047.34   83096.01    608.061620         83197.365
2025-04-03 12:00:00   83047.00   83147.95   81916.01   81949.06   1872.330470         82531.980
2025-04-03 13:00:00   81890.00   82792.46   81802.41   82373.58   2339.513900         82297.435
2025-04-03 14:00:00   82161.32   82403.50   81374.94   81532.00   2364.560000         81889.220
2025-04-03 15:00:00   81479.17   82101.42   81316.82   82039.31   2246.654330         81709.120
2025-04-03 16:00:00   82018.24   82448.21   81735.13   81830.56   1010.180980         82091.670
2025-04-03 17:00:00   81816.12   82191.11   81645.71   81830.01    889.366720         81918.410
2025-04-03 18:00:00   81830.00   82317.99   81550.85   82109.45    990.199650         81934.420
2025-04-03 19:00:00   82081.24   82362.41   81869.40   82008.70   1247.726360         82115.905
2025-04-03 20:00:00   81951.95   82421.49   81821.46   82363.99   1289.977490         82121.475
2025-04-03 21:00:00   82347.51   82864.00   82333.87   82717.54    615.389650         82598.935
2025-04-03 22:00:00   82622.80   82869.99   82616.42   82743.46    432.331760         82743.205
2025-04-03 23:00:00   82743.45   83332.20   82533.16   83213.09    755.059260         82932.680
2025-04-04 00:00:00   83178.85   83413.46   83000.02   83046.32   1239.490060         83206.740
2025-04-04 01:00:00   83046.31   83358.50   82618.49   82695.91    989.866530         82988.495
2025-04-04 02:00:00   82695.90   83186.96   82695.90   82910.86    396.197220         82941.430
2025-04-04 03:00:00   82908.28   83069.96   82698.12   82818.52    416.145030         82884.040
2025-04-04 04:00:00   82816.29   82920.19   82615.36   82720.32    664.543690         82767.775
2025-04-04 05:00:00   82720.31   83212.17   82650.44   83200.00    628.674900         82931.305
2025-04-04 06:00:00   83199.99   83264.16   83048.99   83054.72    400.851920         83156.575
2025-04-04 07:00:00   83054.72   84000.00   83054.73   83992.85   1397.795340         83527.365
2025-04-04 08:00:00   83992.85   84650.00   83992.85   84415.99   1616.222360         84321.425
2025-04-04 09:00:00   84416.00   84720.00   84159.99   84571.38    882.781020         84439.995
2025-04-04 10:00:00   84565.91   84690.00   82442.07   82567.03   4808.433620         83566.035
2025-04-04 11:00:00   82565.20   82768.09   81743.16   82680.45   2375.098530         82255.625
2025-04-04 12:00:00   82495.01   83200.00   82248.32   82879.99   2300.224390         82724.160
2025-04-04 13:00:00   82872.29   83507.19   82144.95   83335.99   2211.631200         82826.070
2025-04-04 14:00:00   83296.79   83510.00   81877.08   82573.98   2330.639910         82693.540
2025-04-04 15:00:00   82488.88   83716.00   82573.98   82860.00   3250.109090         83144.990
2025-04-04 16:00:00   82860.00   83555.00   82738.00   83392.70   1380.469680         83146.500
2025-04-04 17:00:00   83376.82   84620.01   83032.00   84460.00   2047.817960         83826.005
2025-04-04 18:00:00   84459.99   84584.91   83775.18   83989.87   1110.660340         84180.045
2025-04-04 19:00:00   83950.01   84460.00   83788.01   84009.99    835.236800         84124.005
2025-04-04 20:00:00   83984.52   84282.00   83516.30   84164.02    600.667970         83899.150
2025-04-04 21:00:00   84119.66   84450.00   83941.43   84185.80    427.973480         84195.715
2025-04-04 22:00:00   84185.80   84271.28   84018.86   84056.74    252.048790         84145.070
2025-04-04 23:00:00   84056.74   84100.00   83650.12   83889.87    351.959930         83875.060
2025-04-05 00:00:00   83827.93   83889.88   83473.56   83787.60    475.672600         83681.720
2025-04-05 01:00:00   83787.59   84266.00   83787.60   83979.87    382.389280         84026.800
2025-04-05 02:00:00   83979.88   84094.57   83834.09   83976.61    371.161590         83964.330
2025-04-05 03:00:00   83957.88   83976.61   83638.69   83624.01    476.529100         83807.650
2025-04-05 04:00:00   83621.73   83868.00   83620.33   83677.75    332.912190         83744.165
2025-04-05 05:00:00   83677.74   83863.36   83634.31   83688.67    231.145480         83748.835
2025-04-05 06:00:00   83685.29   83724.39   83341.99   83477.30    394.810900         83533.190
2025-04-05 07:00:00   83458.38   83558.65   83382.02   83525.34    322.081660         83470.335
2025-04-05 08:00:00   83516.06   83648.63   83375.57   83519.96    287.897550         83512.100
2025-04-05 09:00:00   83519.76   83865.10   83519.97   83843.29    329.664190         83692.535
2025-04-05 10:00:00   83843.28   83894.70   83586.56   83641.51    209.986820         83740.630
2025-04-05 11:00:00   83641.50   83700.52   83443.48   83452.69    405.741720         83572.000
2025-04-05 12:00:00   83429.19   83550.68   83157.33   83281.41    447.965670         83354.005
2025-04-05 13:00:00   83269.60   83335.56   82542.61   82755.29    932.445730         82939.085
2025-04-05 14:00:00   82726.00   83026.00   82708.69   82914.67    391.756120         82867.345
2025-04-05 15:00:00   82904.05   82914.67   82394.00   82618.26    804.805110         82654.335
2025-04-05 16:00:00   82611.80   82827.37   82609.55   82739.96    246.003240         82718.460
2025-04-05 17:00:00   82729.32   82953.20   82681.65   82869.53    200.383810         82817.425
2025-04-05 18:00:00   82854.80   83109.46   82869.53   83036.13    308.689730         82989.495
2025-04-05 19:00:00   83036.13   83146.00   82781.96   82860.00    219.106660         82963.980
2025-04-05 20:00:00   82859.99   83113.67   82833.00   83075.47    404.280100         82973.335
2025-04-05 21:00:00   83060.59   83237.34   82904.31   82913.89    332.106360         83070.825
2025-04-05 22:00:00   82913.88   83212.18   82913.88   83188.41    389.579730         83063.030
2025-04-05 23:00:00   83182.63   83688.00   83150.01   83537.99    463.289340         83419.005
2025-04-06 00:00:00   83516.00   83620.01   83442.01   83527.22    286.569340         83531.010
2025-04-06 01:00:00   83502.00   83817.63   83425.12   83428.97    364.621070         83621.375
2025-04-06 02:00:00   83428.97   83494.43   83281.08   83300.01    242.196590         83387.755
2025-04-06 03:00:00   83300.00   83403.46   83191.49   83344.14    316.068650         83297.475
2025-04-06 04:00:00   83342.00   83500.00   83249.11   83499.99    204.860260         83374.555
2025-04-06 05:00:00   83499.99   83533.01   83319.62   83450.01    301.553800         83426.315
2025-04-06 06:00:00   83450.00   83468.00   83159.99   83110.24    211.742960         83313.995
2025-04-06 07:00:00   83110.23   83207.22   83024.97   83024.96    287.043010         83116.095
2025-04-06 08:00:00   82970.85   83051.33   82750.01   83034.26    452.852960         82900.670
2025-04-06 09:00:00   83005.99   83172.00   82933.97   83075.15    141.857040         83052.985
2025-04-06 10:00:00   83041.42   83075.15   82762.66   82870.25    266.712280         82918.905
2025-04-06 11:00:00   82854.11   82921.48   82671.31   82855.99    346.585340         82796.395
2025-04-06 12:00:00   82814.35   82981.14   82646.00   82697.99    379.847540         82813.570
2025-04-06 13:00:00   82674.00   82839.87   82280.00   82306.01    877.135970         82559.935
2025-04-06 14:00:00   82260.48   82793.00   82264.01   82667.07    748.433510         82528.505
2025-04-06 15:00:00   82651.22   82819.74   82416.33   82548.36    525.555680         82618.035
2025-04-06 16:00:00   82512.93   82554.15   81987.01   81970.00   1125.690300         82270.580
2025-04-06 17:00:00   81891.23   81982.43   80728.59   80808.81   2740.821850         81355.510
2025-04-06 18:00:00   80649.02   80808.81   78695.01   79107.30   4445.727470         79751.910
2025-04-06 19:00:00   78959.90   79859.73   78973.20   79614.35   1892.030920         79416.465
2025-04-06 20:00:00   79512.22   79890.16   78578.46   78867.99   2279.675640         79234.310
2025-04-06 21:00:00   78720.00   79681.81   78841.98   78950.61   1342.552070         79261.895
2025-04-06 22:00:00   78585.00   79130.44   77865.04   78063.66   4224.448810         78497.740
2025-04-06 23:00:00   77901.73   78709.16   77210.95   78430.00   3938.131300         77960.055
2025-04-07 00:00:00   78339.90   78520.00   77448.63   78327.87   2646.042640         77984.315
2025-04-07 01:00:00   78327.86   79347.46   78323.17   79142.01   2024.954770         78835.315
2025-04-07 02:00:00   79098.66   79220.00   78426.02   78447.42   1208.896480         78823.010
2025-04-07 03:00:00   78416.16   78507.81   77385.12   77707.77   2435.513620         77946.465
2025-04-07 04:00:00   77682.64   77984.00   76694.38   76989.92   3062.664950         77339.190
2025-04-07 05:00:00   76987.40   77500.00   76701.26   76942.82   2272.401080         77100.630
2025-04-07 06:00:00   76906.31   77299.99   74678.98   74810.01   9248.786710         75989.485
2025-04-07 07:00:00   74770.21   75491.06   74610.00   75126.01   4359.455260         75050.530
2025-04-07 08:00:00   75085.74   76843.47   75126.01   76266.89   3895.359550         75984.740
2025-04-07 09:00:00   76190.39   76792.00   75806.00   76274.56   2059.593440         76299.000
2025-04-07 10:00:00   76233.05   77577.88   76162.48   76983.60   2616.795250         76870.180
2025-04-07 11:00:00   76909.38   77400.00   76489.98   76685.62   1472.784940         76944.990
2025-04-07 12:00:00   76685.62   77666.00   76488.64   77335.89   2701.168590         77077.320
2025-04-07 13:00:00   77159.90   78498.93   75836.82   78365.47   4749.878310         77167.875
2025-04-07 14:00:00   78300.00   81243.58   77977.70   79033.11  15098.554220         79610.640
2025-04-07 15:00:00   78926.81   79376.00   77806.03   78479.90   5159.370340         78591.015
2025-04-07 16:00:00   78312.00   78584.21   77404.00   77434.01   2210.730670         77994.105
2025-04-07 17:00:00   77434.00   79200.00   77434.01   79074.50   3328.433570         78317.005
2025-04-07 18:00:00   78960.70   79365.46   78305.74   78484.91   1817.828810         78835.600
2025-04-07 19:00:00   78432.84   78961.92   78109.98   78130.44   1473.927920         78535.950
2025-04-07 20:00:00   78102.91   79128.82   78130.43   78955.26    788.568240         78629.625
2025-04-07 21:00:00   78884.51   79591.92   78684.23   79239.42    997.044590         79138.075
2025-04-07 22:00:00   79228.63   80218.88   79230.00   79956.47   1195.426350         79724.440
2025-04-07 23:00:00   79900.01   80083.99   79120.96   79163.24   1563.350590         79602.475
2025-04-08 00:00:00   79124.74   79599.99   79000.00   79020.04   1021.922180         79299.995

In [20]:
data["signal"]= np.where(data["close"] > data["high_low_average"], 1, -1)
data

                          open       high        low      close        volume  high_low_average  signal
timestamp
2025-03-30 10:00:00   83285.53   83359.90   83064.17   83120.87    223.190610         83212.035      -1
2025-03-30 11:00:00   83120.86   83360.31   82989.27   83111.76    334.935950         83174.790      -1
2025-03-30 12:00:00   83109.65   83268.05   82989.26   83072.76    356.536890         83128.655      -1
2025-03-30 13:00:00   83068.13   83155.17   82662.01   82678.42   1050.992850         82908.590      -1
2025-03-30 14:00:00   82678.42   83043.59   82630.02   82803.28    466.767080         82836.805      -1
2025-03-30 15:00:00   82803.28   83067.90   82732.02   82729.57    280.141080         82899.960      -1
2025-03-30 16:00:00   82710.48   82816.00   82201.89   82284.01    603.144990         82508.945      -1
2025-03-30 17:00:00   82250.00   82577.99   82059.70   82415.53    398.110750         82318.845       1
2025-03-30 18:00:00   82415.53   82799.99   82415.54   82729.65    321.945930         82607.765       1
2025-03-30 19:00:00   82707.83   82908.11   82550.05   82548.81    258.331760         82729.080      -1
2025-03-30 20:00:00   82544.80   82650.95   82400.01   82554.73    201.030050         82525.480       1
2025-03-30 21:00:00   82554.73   82703.94   82069.41   82237.68    258.821660         82386.675      -1
2025-03-30 22:00:00   82086.00   82757.70   81577.86   82438.00    997.389990         82167.780       1
2025-03-30 23:00:00   82391.98   82442.94   81964.95   82389.99    621.081980         82203.945       1
2025-03-31 00:00:00   82368.48   82444.89   81333.98   81646.89   1156.904700         81889.435      -1
2025-03-31 01:00:00   81534.78   82272.72   81543.25   81953.03    778.608830         81907.985       1
2025-03-31 02:00:00   81900.00   82179.25   81644.00   81922.30    652.558370         81911.625       1
2025-03-31 03:00:00   81906.00   82030.00   81490.01   81530.00    549.387110         81760.005      -1
2025-03-31 04:00:00   81529.09   81879.16   81417.47   81846.01    489.047800         81648.315       1
2025-03-31 05:00:00   81830.00   82305.57   81846.00   82166.99    520.567410         82075.785       1
2025-03-31 06:00:00   82166.98   82267.66   81938.55   82052.83    641.586310         82103.105      -1
2025-03-31 07:00:00   82046.00   82303.58   81765.75   81933.51    776.648170         82034.665      -1
2025-03-31 08:00:00   81908.19   82263.74   81914.38   81899.15    762.807570         82089.060      -1
2025-03-31 09:00:00   81889.34   81960.56   81371.68   81455.58    965.895570         81666.120      -1
2025-03-31 10:00:00   81451.90   82215.91   81325.68   82174.16    713.595130         81770.795       1
2025-03-31 11:00:00   82174.16   82272.00   81893.04   82205.51    980.634120         82082.520       1
2025-03-31 12:00:00   82185.63   83169.82   81939.36   82768.74   1527.489470         82554.590       1
2025-03-31 13:00:00   82706.58   82866.02   81761.36   82507.99   2027.952580         82313.690       1
2025-03-31 14:00:00   82507.49   83746.23   82507.99   83499.18   2160.575470         83127.110       1
2025-03-31 15:00:00   83499.18   83943.08   83411.39   83418.78   1241.909230         83677.235      -1
2025-03-31 16:00:00   83418.78   83694.29   83273.18   83288.89    658.286560         83483.735      -1
2025-03-31 17:00:00   83261.76   83545.55   82586.00   82680.34    667.392630         83065.775      -1
2025-03-31 18:00:00   82676.00   83566.00   82680.35   83291.42    810.730870         83123.175       1
2025-03-31 19:00:00   83282.00   83443.38   82412.81   82462.27    798.209250         82928.095      -1
2025-03-31 20:00:00   82405.02   82846.20   82376.82   82431.32    701.198120         82611.510      -1
2025-03-31 21:00:00   82422.00   82752.18   82431.32   82563.99    342.528650         82591.750      -1
2025-03-31 22:00:00   82553.00   82571.98   82280.15   82409.99    260.876470         82426.065      -1
2025-03-31 23:00:00   82388.21   82886.80   82295.86   82550.01    383.748460         82591.330      -1
2025-04-01 00:00:00   82490.76   82837.38   82432.74   82651.10    526.959220         82635.060       1
2025-04-01 01:00:00   82605.34   82741.80   82470.01   82704.20    440.090930         82605.905       1
2025-04-01 02:00:00   82685.24   83120.00   82649.34   83100.00    522.782460         82884.670       1
2025-04-01 03:00:00   83065.23   83256.80   82926.10   82962.84    526.153630         83091.450      -1
2025-04-01 04:00:00   82914.39   83235.96   82887.01   83060.00    425.378740         83061.485      -1
2025-04-01 05:00:00   83031.57   83329.99   82994.08   83006.67    348.443640         83162.035      -1
2025-04-01 06:00:00   83000.01   83494.25   82900.01   83454.76    425.660160         83197.130       1
2025-04-01 07:00:00   83454.75   83597.07   83387.07   83445.50    622.585510         83492.070      -1
2025-04-01 08:00:00   83410.00   84207.55   83445.50   84121.94   1217.292790         83826.525       1
2025-04-01 09:00:00   84121.93   84395.46   84121.94   84362.00   1018.971860         84258.700       1
2025-04-01 10:00:00   84311.68   84504.74   84169.81   84175.99    914.761180         84337.275      -1
2025-04-01 11:00:00   84161.58   84203.00   83846.38   83930.30    854.543510         84024.690      -1
2025-04-01 12:00:00   83924.52   84154.22   83628.16   83615.26    734.992560         83891.190      -1
2025-04-01 13:00:00   83596.00   83912.62   83430.69   83618.23   1152.681040         83671.655      -1
2025-04-01 14:00:00   83480.00   84350.00   82637.99   84195.92   2522.860470         83493.995       1
2025-04-01 15:00:00   84182.89   85499.55   84195.92   85280.87   2484.930750         84847.735       1
2025-04-01 16:00:00   85275.21   85493.00   84815.32   85119.99   1208.484920         85154.160      -1
2025-04-01 17:00:00   85028.12   85333.33   84904.25   85117.85    775.262400         85118.790      -1
2025-04-01 18:00:00   85038.01   85183.46   84726.64   85126.68    742.895530         84955.050       1
2025-04-01 19:00:00   85095.97   85184.89   84836.97   84972.01    897.453260         85010.930      -1
2025-04-01 20:00:00   84920.48   85350.00   84782.36   85231.28    528.396380         85066.180       1
2025-04-01 21:00:00   85231.28   85476.86   85138.01   85223.84    325.841410         85307.435      -1
2025-04-01 22:00:00   85219.90   85483.38   85114.88   85099.99    477.113020         85299.130      -1
2025-04-01 23:00:00   85084.80   85579.46   84991.80   85158.34    495.861600         85285.630      -1
2025-04-02 00:00:00   85158.35   85255.95   84940.78   84964.49    472.950930         85098.365      -1
2025-04-02 01:00:00   84956.31   85213.12   84870.85   85147.30    597.768960         85041.985       1
2025-04-02 02:00:00   85101.08   85174.89   84665.22   84714.36    850.774360         84920.055      -1
2025-04-02 03:00:00   84706.21   84904.00   84532.43   84550.00    475.509660         84718.215      -1
2025-04-02 04:00:00   84517.00   84726.42   84475.46   84607.00    444.662260         84600.940       1
2025-04-02 05:00:00   84567.60   84607.00   84117.15   84100.00    550.684820         84362.075      -1
2025-04-02 06:00:00   84046.00   84371.59   83931.29   84125.99    646.497800         84151.440      -1
2025-04-02 07:00:00   84120.00   84462.16   84039.79   84426.33    642.707380         84250.975       1
2025-04-02 08:00:00   84351.77   84762.72   84262.74   84677.04    535.256650         84512.730       1
2025-04-02 09:00:00   84635.60   85450.00   84677.04   85019.62    910.863510         85063.520      -1
2025-04-02 10:00:00   85015.50   85299.45   84851.98   84867.92    592.830320         85075.715      -1
2025-04-02 11:00:00   84746.18   84985.77   84558.69   84566.91    463.522710         84772.230      -1
2025-04-02 12:00:00   84554.43   85054.78   84487.90   85049.99    742.570820         84771.340       1
2025-04-02 13:00:00   84983.68   86136.36   84531.34   85215.82   2792.280520         85333.850      -1
2025-04-02 14:00:00   85181.52   86000.00   85215.79   85877.75   2062.013420         85607.895       1
2025-04-02 15:00:00   85811.20   87333.00   85877.74   86757.67   5585.702140         86605.370       1
2025-04-02 16:00:00   86697.78   87221.99   86603.77   87065.18   2549.141960         86912.880       1
2025-04-02 17:00:00   87039.92   87333.00   86391.97   86615.33   2025.448110         86862.485      -1
2025-04-02 18:00:00   86581.55   86751.79   86236.46   86286.02    685.232900         86494.125      -1
2025-04-02 19:00:00   86286.03   87000.00   86206.56   86900.02    812.773360         86603.280       1
2025-04-02 20:00:00   86774.82   88500.00   85299.48   85659.99   7832.634990         86899.740      -1
2025-04-02 21:00:00   85615.64   85743.22   84260.00   84855.99   1793.310350         85001.610      -1
2025-04-02 22:00:00   84582.79   84855.98   82737.64   82821.59   3036.674270         83796.810      -1
2025-04-02 23:00:00   82560.59   82845.42   82384.65   82516.29   2829.644800         82615.035      -1
2025-04-03 00:00:00   82436.40   83424.72   82212.01   83227.55   1848.780370         82818.365       1
2025-04-03 01:00:00   83190.00   83998.02   83138.90   83761.62   1735.380820         83568.460       1
2025-04-03 02:00:00   83750.94   83894.91   83284.44   83768.01   1422.271460         83589.675       1
2025-04-03 03:00:00   83743.89   83792.58   83349.66   83483.97    638.138130         83571.120      -1
2025-04-03 04:00:00   83454.94   83735.85   83300.00   83558.80    630.552660         83517.925       1
2025-04-03 05:00:00   83556.93   83709.48   83348.26   83343.75    457.594970         83528.870      -1
2025-04-03 06:00:00   83300.00   83415.47   83008.74   83058.65    568.508340         83212.105      -1
2025-04-03 07:00:00   83036.47   83498.10   83025.01   83456.75    774.524070         83261.555       1
2025-04-03 08:00:00   83456.74   83788.23   83456.76   83679.99    821.936770         83622.495       1
2025-04-03 09:00:00   83677.10   83766.69   83449.92   83483.05    539.185410         83608.305      -1
2025-04-03 10:00:00   83469.49   83749.99   83170.66   83220.01   1239.616160         83460.325      -1
2025-04-03 11:00:00   83129.71   83347.39   83047.34   83096.01    608.061620         83197.365      -1
2025-04-03 12:00:00   83047.00   83147.95   81916.01   81949.06   1872.330470         82531.980      -1
2025-04-03 13:00:00   81890.00   82792.46   81802.41   82373.58   2339.513900         82297.435       1
2025-04-03 14:00:00   82161.32   82403.50   81374.94   81532.00   2364.560000         81889.220      -1
2025-04-03 15:00:00   81479.17   82101.42   81316.82   82039.31   2246.654330         81709.120       1
2025-04-03 16:00:00   82018.24   82448.21   81735.13   81830.56   1010.180980         82091.670      -1
2025-04-03 17:00:00   81816.12   82191.11   81645.71   81830.01    889.366720         81918.410      -1
2025-04-03 18:00:00   81830.00   82317.99   81550.85   82109.45    990.199650         81934.420       1
2025-04-03 19:00:00   82081.24   82362.41   81869.40   82008.70   1247.726360         82115.905      -1
2025-04-03 20:00:00   81951.95   82421.49   81821.46   82363.99   1289.977490         82121.475       1
2025-04-03 21:00:00   82347.51   82864.00   82333.87   82717.54    615.389650         82598.935       1
2025-04-03 22:00:00   82622.80   82869.99   82616.42   82743.46    432.331760         82743.205       1
2025-04-03 23:00:00   82743.45   83332.20   82533.16   83213.09    755.059260         82932.680       1
2025-04-04 00:00:00   83178.85   83413.46   83000.02   83046.32   1239.490060         83206.740      -1
2025-04-04 01:00:00   83046.31   83358.50   82618.49   82695.91    989.866530         82988.495      -1
2025-04-04 02:00:00   82695.90   83186.96   82695.90   82910.86    396.197220         82941.430      -1
2025-04-04 03:00:00   82908.28   83069.96   82698.12   82818.52    416.145030         82884.040      -1
2025-04-04 04:00:00   82816.29   82920.19   82615.36   82720.32    664.543690         82767.775      -1
2025-04-04 05:00:00   82720.31   83212.17   82650.44   83200.00    628.674900         82931.305       1
2025-04-04 06:00:00   83199.99   83264.16   83048.99   83054.72    400.851920         83156.575      -1
2025-04-04 07:00:00   83054.72   84000.00   83054.73   83992.85   1397.795340         83527.365       1
2025-04-04 08:00:00   83992.85   84650.00   83992.85   84415.99   1616.222360         84321.425       1
2025-04-04 09:00:00   84416.00   84720.00   84159.99   84571.38    882.781020         84439.995       1
2025-04-04 10:00:00   84565.91   84690.00   82442.07   82567.03   4808.433620         83566.035      -1
2025-04-04 11:00:00   82565.20   82768.09   81743.16   82680.45   2375.098530         82255.625       1
2025-04-04 12:00:00   82495.01   83200.00   82248.32   82879.99   2300.224390         82724.160       1
2025-04-04 13:00:00   82872.29   83507.19   82144.95   83335.99   2211.631200         82826.070       1
2025-04-04 14:00:00   83296.79   83510.00   81877.08   82573.98   2330.639910         82693.540      -1
2025-04-04 15:00:00   82488.88   83716.00   82573.98   82860.00   3250.109090         83144.990      -1
2025-04-04 16:00:00   82860.00   83555.00   82738.00   83392.70   1380.469680         83146.500       1
2025-04-04 17:00:00   83376.82   84620.01   83032.00   84460.00   2047.817960         83826.005       1
2025-04-04 18:00:00   84459.99   84584.91   83775.18   83989.87   1110.660340         84180.045      -1
2025-04-04 19:00:00   83950.01   84460.00   83788.01   84009.99    835.236800         84124.005      -1
2025-04-04 20:00:00   83984.52   84282.00   83516.30   84164.02    600.667970         83899.150       1
2025-04-04 21:00:00   84119.66   84450.00   83941.43   84185.80    427.973480         84195.715      -1
2025-04-04 22:00:00   84185.80   84271.28   84018.86   84056.74    252.048790         84145.070      -1
2025-04-04 23:00:00   84056.74   84100.00   83650.12   83889.87    351.959930         83875.060       1
2025-04-05 00:00:00   83827.93   83889.88   83473.56   83787.60    475.672600         83681.720       1
2025-04-05 01:00:00   83787.59   84266.00   83787.60   83979.87    382.389280         84026.800      -1
2025-04-05 02:00:00   83979.88   84094.57   83834.09   83976.61    371.161590         83964.330       1
2025-04-05 03:00:00   83957.88   83976.61   83638.69   83624.01    476.529100         83807.650      -1
2025-04-05 04:00:00   83621.73   83868.00   83620.33   83677.75    332.912190         83744.165      -1
2025-04-05 05:00:00   83677.74   83863.36   83634.31   83688.67    231.145480         83748.835      -1
2025-04-05 06:00:00   83685.29   83724.39   83341.99   83477.30    394.810900         83533.190      -1
2025-04-05 07:00:00   83458.38   83558.65   83382.02   83525.34    322.081660         83470.335       1
2025-04-05 08:00:00   83516.06   83648.63   83375.57   83519.96    287.897550         83512.100       1
2025-04-05 09:00:00   83519.76   83865.10   83519.97   83843.29    329.664190         83692.535       1
2025-04-05 10:00:00   83843.28   83894.70   83586.56   83641.51    209.986820         83740.630      -1
2025-04-05 11:00:00   83641.50   83700.52   83443.48   83452.69    405.741720         83572.000      -1
2025-04-05 12:00:00   83429.19   83550.68   83157.33   83281.41    447.965670         83354.005      -1
2025-04-05 13:00:00   83269.60   83335.56   82542.61   82755.29    932.445730         82939.085      -1
2025-04-05 14:00:00   82726.00   83026.00   82708.69   82914.67    391.756120         82867.345       1
2025-04-05 15:00:00   82904.05   82914.67   82394.00   82618.26    804.805110         82654.335      -1
2025-04-05 16:00:00   82611.80   82827.37   82609.55   82739.96    246.003240         82718.460       1
2025-04-05 17:00:00   82729.32   82953.20   82681.65   82869.53    200.383810         82817.425       1
2025-04-05 18:00:00   82854.80   83109.46   82869.53   83036.13    308.689730         82989.495       1
2025-04-05 19:00:00   83036.13   83146.00   82781.96   82860.00    219.106660         82963.980      -1
2025-04-05 20:00:00   82859.99   83113.67   82833.00   83075.47    404.280100         82973.335       1
2025-04-05 21:00:00   83060.59   83237.34   82904.31   82913.89    332.106360         83070.825      -1
2025-04-05 22:00:00   82913.88   83212.18   82913.88   83188.41    389.579730         83063.030       1
2025-04-05 23:00:00   83182.63   83688.00   83150.01   83537.99    463.289340         83419.005       1
2025-04-06 00:00:00   83516.00   83620.01   83442.01   83527.22    286.569340         83531.010      -1
2025-04-06 01:00:00   83502.00   83817.63   83425.12   83428.97    364.621070         83621.375      -1
2025-04-06 02:00:00   83428.97   83494.43   83281.08   83300.01    242.196590         83387.755      -1
2025-04-06 03:00:00   83300.00   83403.46   83191.49   83344.14    316.068650         83297.475       1
2025-04-06 04:00:00   83342.00   83500.00   83249.11   83499.99    204.860260         83374.555       1
2025-04-06 05:00:00   83499.99   83533.01   83319.62   83450.01    301.553800         83426.315       1
2025-04-06 06:00:00   83450.00   83468.00   83159.99   83110.24    211.742960         83313.995      -1
2025-04-06 07:00:00   83110.23   83207.22   83024.97   83024.96    287.043010         83116.095      -1
2025-04-06 08:00:00   82970.85   83051.33   82750.01   83034.26    452.852960         82900.670       1
2025-04-06 09:00:00   83005.99   83172.00   82933.97   83075.15    141.857040         83052.985       1
2025-04-06 10:00:00   83041.42   83075.15   82762.66   82870.25    266.712280         82918.905      -1
2025-04-06 11:00:00   82854.11   82921.48   82671.31   82855.99    346.585340         82796.395       1
2025-04-06 12:00:00   82814.35   82981.14   82646.00   82697.99    379.847540         82813.570      -1
2025-04-06 13:00:00   82674.00   82839.87   82280.00   82306.01    877.135970         82559.935      -1
2025-04-06 14:00:00   82260.48   82793.00   82264.01   82667.07    748.433510         82528.505       1
2025-04-06 15:00:00   82651.22   82819.74   82416.33   82548.36    525.555680         82618.035      -1
2025-04-06 16:00:00   82512.93   82554.15   81987.01   81970.00   1125.690300         82270.580      -1
2025-04-06 17:00:00   81891.23   81982.43   80728.59   80808.81   2740.821850         81355.510      -1
2025-04-06 18:00:00   80649.02   80808.81   78695.01   79107.30   4445.727470         79751.910      -1
2025-04-06 19:00:00   78959.90   79859.73   78973.20   79614.35   1892.030920         79416.465       1
2025-04-06 20:00:00   79512.22   79890.16   78578.46   78867.99   2279.675640         79234.310      -1
2025-04-06 21:00:00   78720.00   79681.81   78841.98   78950.61   1342.552070         79261.895      -1
2025-04-06 22:00:00   78585.00   79130.44   77865.04   78063.66   4224.448810         78497.740      -1
2025-04-06 23:00:00   77901.73   78709.16   77210.95   78430.00   3938.131300         77960.055       1
2025-04-07 00:00:00   78339.90   78520.00   77448.63   78327.87   2646.042640         77984.315       1
2025-04-07 01:00:00   78327.86   79347.46   78323.17   79142.01   2024.954770         78835.315       1
2025-04-07 02:00:00   79098.66   79220.00   78426.02   78447.42   1208.896480         78823.010      -1
2025-04-07 03:00:00   78416.16   78507.81   77385.12   77707.77   2435.513620         77946.465      -1
2025-04-07 04:00:00   77682.64   77984.00   76694.38   76989.92   3062.664950         77339.190      -1
2025-04-07 05:00:00   76987.40   77500.00   76701.26   76942.82   2272.401080         77100.630      -1
2025-04-07 06:00:00   76906.31   77299.99   74678.98   74810.01   9248.786710         75989.485      -1
2025-04-07 07:00:00   74770.21   75491.06   74610.00   75126.01   4359.455260         75050.530       1
2025-04-07 08:00:00   75085.74   76843.47   75126.01   76266.89   3895.359550         75984.740       1

In [4]:
#import and format the data
h5_db= Hdf5Client("Coinbase")
data= h5_db.get_data("BTC-USDT", from_time= 0, to_time= int(time.time() * 1000))
data= resample_timeframe(data, "5m")
data

                          open       high        low      close    volume
timestamp
2025-06-17 03:10:00  107579.52  107624.10  107601.03  107568.34  0.125969
2025-06-17 03:15:00  107564.65  107613.31  107486.13  107474.13  0.097387
2025-06-17 03:20:00  107506.26  107553.46  107469.06  107467.28  0.741257
2025-06-17 03:25:00  107503.53  107546.46  107439.28  107392.54  0.318215
2025-06-17 03:30:00  107430.00  107561.31  107430.00  107553.27  5.839049
2025-06-17 03:35:00  107533.41  107636.20  107523.13  107537.55  0.853388
2025-06-17 03:40:00  107528.79  107600.25  107518.40  107579.58  0.419010
2025-06-17 03:45:00  107626.93  107724.22  107626.94  107645.88  0.665210
2025-06-17 03:50:00  107683.86  107683.86  107571.98  107576.65  0.803371
2025-06-17 03:55:00  107578.07  107603.73  107578.07  107597.97  0.199888
2025-06-17 04:00:00  107595.90  107673.15  107597.73  107580.81  1.269128
2025-06-17 04:05:00  107534.43  107669.88  107564.60  107636.12  0.892287
2025-06-17 04:10:00  107551.19  107697.31  107642.99  107628.48  0.862941
2025-06-17 04:15:00  107591.50  107678.30  107559.30  107559.48  0.518679
2025-06-17 04:20:00  107512.44  107600.94  107505.13  107555.04  0.652513
2025-06-17 04:25:00  107507.29  107574.56  107491.03  107433.94  0.398500
2025-06-17 04:30:00  107428.36  107448.62  107400.97  107415.70  0.513550
2025-06-17 04:35:00  107387.08  107409.30  107342.76  107355.53  0.125386
2025-06-17 04:40:00  107341.18  107394.31  107315.10  107342.95  0.352741
2025-06-17 04:45:00  107353.43  107420.75  107353.43  107420.75  0.267082
2025-06-17 04:50:00  107430.38  107430.38  107390.56  107327.61  0.053789
2025-06-17 04:55:00  107341.34  107428.54  107341.34  107317.10  0.341991
2025-06-17 05:00:00  107333.64  107395.00  107333.64  107388.80  0.161476
2025-06-17 05:05:00  107367.16  107367.16  107360.33  107314.09  0.123447
2025-06-17 05:10:00  107263.33  107294.65  107269.65  107294.65  0.147394
2025-06-17 05:15:00  107141.18  107300.80  107194.28  107300.80  0.949571
2025-06-17 05:20:00  107037.55  107155.90  107083.63  107111.43  0.607156
2025-06-17 05:25:00  107085.09  107268.82  107108.49  107254.40  0.745025
2025-06-17 05:30:00  107185.65  107271.00  107199.96  107243.44  0.115075
2025-06-17 05:35:00  107225.04  107298.33  107225.04  107292.83  0.029694
2025-06-17 05:40:00  107182.86  107273.09  107209.12  107087.93  0.427593
2025-06-17 05:45:00  107087.34  107159.93  107087.34  107047.94  0.103644
2025-06-17 05:50:00  107073.90  107139.20  107072.60  107136.85  0.116217
2025-06-17 05:55:00  107100.68  107152.35  107079.04  107098.06  0.823745
2025-06-17 06:00:00  107089.97  107166.20  107089.97  107131.55  0.327855
2025-06-17 06:05:00  107061.62  107195.93  107070.50  107195.93  0.519318
2025-06-17 06:10:00  107205.33  107222.26  107192.68  107189.70  0.126373
2025-06-17 06:15:00  107179.24  107204.40  107021.93  107022.92  0.729479
2025-06-17 06:20:00  107006.60  107057.71  106953.87  106970.45  0.169487
2025-06-17 06:25:00  106943.37  107001.42  106943.37  107001.42  0.083796
2025-06-17 06:30:00  106958.98  107006.20  106899.61  106980.52  1.018722
2025-06-17 06:35:00  106940.26  106963.92  106916.62  106925.18  0.460951
2025-06-17 06:40:00  106948.52  106983.13  106942.87  106855.12  0.827971
2025-06-17 06:45:00  106855.10  106888.36  106775.11  106781.47  1.551045
2025-06-17 06:50:00  106785.98  106892.26  106785.98  106858.53  0.227419
2025-06-17 06:55:00  106812.06  106829.39  106798.37  106793.75  0.114404
2025-06-17 07:00:00  106819.11  106876.57  106819.11  106802.68  0.236648
2025-06-17 07:05:00  106833.70  106880.40  106815.15  106815.33  0.143511
2025-06-17 07:10:00  106810.52  106839.52  106755.58  106721.29  0.324657
2025-06-17 07:15:00  106693.46  106755.99  106704.12  106719.21  0.248762
2025-06-17 07:20:00  106636.20  106664.15  106587.69  106592.20  0.568029
2025-06-17 07:25:00  106583.42  106622.06  106573.89  106506.84  0.559458
2025-06-17 07:30:00  106544.18  106675.57  106547.39  106574.10  0.806967
2025-06-17 07:35:00  106546.63  106699.61  106546.63  106611.96  0.238749
2025-06-17 07:40:00  106601.30  106657.57  106601.30  106657.57  0.190849
2025-06-17 07:45:00  106656.71  106721.94  106658.13  106716.75  0.347074
2025-06-17 07:50:00  106708.97  106730.58  106708.97  106730.58  0.026440
2025-06-17 07:55:00  106748.56  106781.76  106748.56  106721.48  0.723170
2025-06-17 08:00:00  106660.00  106779.11  106660.00  106723.31  0.200146
2025-06-17 08:05:00  106670.41  106729.58  106670.41  106695.28  0.146140
2025-06-17 08:10:00  106711.22  106772.72  106714.03  106689.49  0.490902
2025-06-17 08:15:00  106707.26  106730.44  106687.72  106720.72  0.104921
2025-06-17 08:20:00  106698.80  106709.05  106667.88  106612.16  0.370955
2025-06-17 08:25:00  106623.77  106812.73  106623.78  106812.73  0.085485
2025-06-17 08:30:00  106779.53  106825.89  106779.53  106748.12  0.073734
2025-06-17 08:35:00  106642.62  106653.38  106572.57  106515.69  0.055193
2025-06-17 08:40:00  106531.01  106571.50  106528.41  106517.16  0.337656
2025-06-17 08:45:00  106556.90  106601.03  106556.90  106529.15  0.394448
2025-06-17 08:50:00  106500.18  106667.58  106500.18  106537.17  0.770752
2025-06-17 08:55:00  106488.54  106593.59  106503.98  106544.34  0.575223
2025-06-17 09:00:00  106536.93  106658.24  106536.63  106624.95  1.958561
2025-06-17 09:05:00  106588.34  106621.65  106422.71  106463.73  1.966602
2025-06-17 09:10:00  106458.14  106509.15  106454.40  106474.58  0.762435
2025-06-17 09:15:00  106451.74  106501.95  106478.95  106452.85  0.274914
2025-06-17 09:20:00  106416.20  106488.86  106421.15  106486.89  1.032382
2025-06-17 09:25:00  106441.01  106445.65  106408.17  106399.76  0.181251
2025-06-17 09:30:00  106371.05  106454.84  106346.97  106341.02  0.271724
2025-06-17 09:35:00  106313.50  106397.56  106256.28  106217.56  1.862793
2025-06-17 09:40:00  106195.06  106283.93  106226.65  106258.79  0.393179
2025-06-17 09:45:00  106231.11  106291.03  106202.24  106236.97  0.296829
2025-06-17 09:50:00  106180.39  106289.48  106195.79  106174.91  0.860157
2025-06-17 09:55:00  106110.00  106195.06  106104.11  106168.20  1.085294
2025-06-17 10:00:00  106117.64  106241.43  106131.34  106111.93  0.926590
2025-06-17 10:05:00  106041.49  106165.66  106063.68  106083.79  0.511694
2025-06-17 10:10:00  106043.96  106153.94  106051.21  106102.64  1.349353
2025-06-17 10:15:00  106112.81  106148.52  106089.90  106071.19  0.510992
2025-06-17 10:20:00  106071.19  106163.14  106041.49  106163.14  1.188838
2025-06-17 10:25:00  106126.00  106126.00  106097.88  106088.50  0.057516
2025-06-17 10:30:00  105998.83  106067.85  105996.78  105960.27  0.211861
2025-06-17 10:35:00  105900.01  105964.45  105868.47  105807.33  3.230770
2025-06-17 10:40:00  105790.66  105866.35  105795.48  105804.72  0.601801
2025-06-17 10:45:00  105771.32  105906.20  105780.51  105857.94  0.613807
2025-06-17 10:50:00  105841.44  105941.17  105833.88  105918.99  1.108683
2025-06-17 10:55:00  105900.75  105965.49  105900.75  105954.36  0.466221
2025-06-17 11:00:00  105905.85  105949.08  105875.23  105800.46  0.494785
2025-06-17 11:05:00  105711.92  105830.31  105740.60  105769.63  0.596277
2025-06-17 11:10:00  105757.47  105792.01  105715.28  105700.00  0.091339
2025-06-17 11:15:00  105687.80  105777.22  105681.82  105642.86  1.168044
2025-06-17 11:20:00  105635.72  105656.91  105602.60  105631.44  0.163706
2025-06-17 11:25:00  105540.67  105569.63  105538.75  105553.93  0.217337
2025-06-17 11:30:00  105606.35  105674.52  105606.35  105627.66  0.690557
2025-06-17 11:35:00  105612.11  105631.69  105593.08  105571.82  0.342877
2025-06-17 11:40:00  105506.83  105576.52  105532.33  105520.82  0.720161
2025-06-17 11:45:00  105514.30  105584.15  105511.82  105552.36  0.578456
2025-06-17 11:50:00  105521.20  105533.97  105531.38  105498.77  0.208265
2025-06-17 11:55:00  105569.83  105676.69  105569.83  105636.80  0.438317
2025-06-17 12:00:00  105567.71  105632.11  105598.82  105612.41  6.294285
2025-06-17 12:05:00  105616.17  105777.07  105616.17  105733.61  1.454456
2025-06-17 12:10:00  105736.04  105846.62  105739.18  105778.44  3.822844